#pragma once

// Mouse Actions
#define MOUSE_INVALID -1
#define MOUSE_PRESS	  0
#define MOUSE_RELEASE 1
#define MOUSE_MOVE    2
#define MOUSE_SCROLL  3
#define MOUSE_ENTER   4
#define MOUSE_LEAVE   5

// Mouse Buttons
#define MOUSE_BUTTON_1 0
#define MOUSE_BUTTON_2 1
#define MOUSE_BUTTON_3 2
#define MOUSE_BUTTON_4 3
#define MOUSE_BUTTON_5 4
#define MOUSE_BUTTON_LEFT     MOUSE_BUTTON_1
#define MOUSE_BUTTON_RIGHT    MOUSE_BUTTON_2
#define MOUSE_BUTTON_MIDDLE   MOUSE_BUTTON_3
#define MOUSE_BUTTON_BACKWARD MOUSE_BUTTON_4
#define MOUSE_BUTTON_FORWARD  MOUSE_BUTTON_5

#define MOUSE_BUTTON_COUNT 5